import turtle
turtle.pensize(5)
turtle.forward(100)
turtle.right(90)
turtle.pencolor("red")
turtle.forward(100)
turtle.right(90)
turtle.pencolor("green")
turtle.forward(100)
turtle.right(90)
turtle.pencolor("blue")
turtle.forward(100)
turtle.right(90)